### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TheBalkanDev** [lovetwice1012/BigBrother-1#5]
### Issue description
The Composer Autoloader not found.

### Prerequisite
No

### How to reproduce
Load the Plugin on the Server.

### Server log(crash dump)

[12:15:42] [Server thread/CRITICAL]: [BigBrother] Composer autoloader not found

**Comment by protectoryt** [comment]
Yea same error lol

**Comment by ProDev69** [comment]
Hmmm

**Comment by lovetwice1012** [comment]
Please install Composer and run `composer install` in console.
